{API_KEY: c657475dd04b433d91e16117a023d536, MANIFEST_FILE: !!python/unicode 'manifest\world_sql_content_91d58facdc14536d9366b300c95a2425.content',
  Manifest: !!python/unicode '/common/destiny_content/sqlite/en/world_sql_content_91d58facdc14536d9366b300c95a2425.content',
  ManifestDirectory: manifest}
