{API_KEY: c657475dd04b433d91e16117a023d536, MANIFEST_FILE: !!python/unicode 'manifest\world_sql_content_023f385e689903fc02464f8a4f2e1430.content',
  Manifest: !!python/unicode '/common/destiny_content/sqlite/en/world_sql_content_023f385e689903fc02464f8a4f2e1430.content',
  ManifestDirectory: manifest}
